variables:
  NODE_ENV: "production"
  JOBLIST_DB_URL: "https://gitlab.com/joblist/workers/-/jobs/artifacts/main/raw/public/joblist.db?job=save-database:on-schedule"

save-database:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run save-companies
    - npm run save-jobs
    - mkdir public
    - mv joblist.db public/
  artifacts:
    paths:
      - public

api_companies:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run api-companies
  artifacts:
    paths:
      - public

pages:on-schedule:
  script:
    - mkdir public
    - curl $JOBLIST_DB_URL > public/joblist.db
  artifacts:
    paths:
      - public
