---
---
stages:
  - dependencies
  - save
  - processing
  - analyze
  - deploy

variables:
  NODE_ENV: "production"

image: node:latest

cache:
  paths:
    - node_modules/
    - .db-github-data/
    - .db-sqlite/

install-dependencies:on-schedule:
  stage: dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install

github-data:on-schedule:
  stage: dependencies
  needs: ["install-dependencies:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run database-git

database-stripe:on-schedule:
  stage: dependencies
  needs: ["install-dependencies:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run database-stripe

save-companies:on-schedule:
  stage: save
  needs: ["github-data:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run save-companies

.save-jobs:on-schedule:
  stage: save
  needs: ["github-data:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run save-jobs

processing-companies:on-schedule:
  stage: processing
  needs: ["save-companies:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run processing-companies

.processing-jobs:on-schedule:
  stage: processing
  needs: ["save-jobs:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run processing-jobs

processing-stripe-companies:on-schedule:
  stage: processing
  needs: ["processing-companies:on-schedule"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run processing-stripe

.heatmap:on-schedule:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run heatmap-agg

analyze:on-schedule:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run analyze-companies
    - npm run analyze-jobs

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv .db-sqlite/joblist.db public/
  artifacts:
    paths:
      - public
  only:
    - schedules
