variables:
  NODE_ENV: "production"

algolia_jobs:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run algolia-jobs

algolia_companies:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run algolia-companies

api_companies:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run api-companies
  artifacts:
    paths:
    - public
