algolia_jobs:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run algolia-jobs

companies_api:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run companies-api
  artifacts:
    paths:
    - public
