---
---
stages:
  - save
  - processing
  - analyze
  - deploy

variables:
  NODE_ENV: "production"

image: node:latest

cache:
  key: joblist-db
  paths:
    - joblist.db

save:on-schedule:
  stage: save
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run save-companies
    - npm run save-jobs

processing:on-schedule:
  stage: processing
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run processing-companies
    - npm run processing-jobs

analyze:on-schedule:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run analyze-companies
    - npm run analyze-jobs

heatmap:on-schedule:
  stage: heatmap
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run heatmap-agg

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv joblist.db public/
  artifacts:
    paths:
      - public
  only:
    - schedules
