variables:
  NODE_ENV: "production"

save-database:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run save-companies
    - npm run save-jobs
    - mkdir public
    - mv joblist.db public/

api_companies:on-schedule:
  image: node:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run api-companies
  artifacts:
    paths:
      - public
