variables:
  NODE_ENV: "production"

save-database:on-schedule:
  image: node:latest
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run save-companies
    - npm run save-jobs
    - mkdir -p public
    - mv joblist.db public/
  artifacts:
    paths:
      - public

.api_companies:on-schedule:
  image: node:latest
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
    - npm run api-companies
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mkdir -p public
  only:
    - schedules
  artifacts:
    paths:
      - public
