---
---
stages:
  - dependencies
  - save
  - processing
  - analyze
  - deploy

variables:
  NODE_ENV: "production"

image: node:latest

cache:
  key: .db-sqlite
  paths:
    - .db-sqlite/*

install-dependencies:on-schedule:
  stage: dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    untracked: true
    paths:
      - node_modules/

github-data:on-schedule:
  stage: dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run database-git
  needs: ["install-dependencies"]
  cache:
    paths:
      - .db-github-data/
  artifacts:
    paths:
      - .db-github-data/

database-stripe:on-schedule:
  stage: dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run database-stripe
  needs: ["install-dependencies"]
  cache:
    paths:
      - .db-sqlite/
  artifacts:
    paths:
      - .db-sqlite/

save-companies:on-schedule:
  stage: save
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run save-companies

save-jobs:on-schedule:
  stage: save
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run save-jobs

processing:on-schedule:
  stage: processing
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run processing-companies
    - npm run processing-jobs
    - npm run processing-stripe

.heatmap:on-schedule:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run heatmap-agg

analyze:on-schedule:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm run analyze-companies
    - npm run analyze-jobs

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv .db-sqlite/joblist.db public/
  artifacts:
    paths:
      - public
  only:
    - schedules
