algolia-jobs:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run algolia-jobs

companies-api:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run companies-api
