algolia_jobs:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run algolia-jobs

api_companies:on-schedule:
  image: node:latest
  only:
    - schedules
  script:
    - npm install
    - npm run api-companies
  artifacts:
    paths:
    - public
