body = "Airbnb operates an online #marketplace and #hospitality service which is accessible via its websites and mobile apps. Members can use the #service to arrange or offer #lodging, primarily #homestays, or #tourism #experiences."
created_at = "2017-06-28T20:24:41.890Z"
is_approved = true
career_page_url = "https://www.airbnb.com/careers/locations/berlin-germany"
slug = "airbnb"
tags = ["marketplace", "hospitality", "service", "lodging", "homestays", "tourism", "experiences"]
title = "Airbnb"
updated_at = "2019-06-16T10:36:08.542Z"
