body = "Amorelie is an online #sexshop"
created_at = "2017-06-28T20:31:52.597Z"
is_approved = true
career_page_url = "http://www.amorelie.de/jobs/"
latitude = 52.5412791
longitude = 13.3901186
slug = "amorelie"
tags = ["sexshop"]
title = "Amorelie"
updated_at = "2019-06-16T10:36:08.537Z"
