body = "Aperto is a  #digital-agency part of IBM interactive Experience (IBM iX); #advertising #marketing #social-media #web-design"
created_at = "2018-02-04T18:12:22.932Z"
is_approved = true
career_page_url = "http://www.aperto.com/en/jobs"
latitude = 52.5278904
longitude = 13.3866469
slug = "aperto-gmbh"
tags = ["digital-agency", "advertising", "marketing", "social-media", "web-design"]
title = "Aperto GmbH"
updated_at = "2019-06-16T10:36:09.736Z"
