body = "#startup provinding an app for #yoga and #fitness practice"
created_at = "2018-02-02T10:46:55.589Z"
is_approved = true
career_page_url = "https://boards.greenhouse.io/asanarebel"
job_board_provider = "greenhouse"
job_board_hostname = "asanarebel"
latitude = 52.5044379
longitude = 13.3785254
slug = "asana-rebel"
tags = ["startup", "yoga", "fitness"]
title = "Asana Rebel"
updated_at = "2019-06-16T10:36:09.742Z"
