body = "The tww airports operating in Berlin and the commercial zone arround. #aviation #logistics #shops"
created_at = "2018-02-09T14:21:50.806Z"
is_approved = true
career_page_url = "http://www.berlin-airport.de/de/unternehmen/jobs-und-karriere/jobboerse/index.php/alle-stellenangebote/alle-anzeigen#skiptoresultlist"
slug = "berlin-airports-fbb---flughafen-berlin-brandenburg"
tags = ["aviation", "logistics", "shops"]
title = "Berlin Airports (FBB - Flughafen Berlin Brandenburg)"
updated_at = "2019-06-16T10:36:09.744Z"
