body = "#travel and hotel booking search engine"
created_at = "2017-06-28T20:20:30.847Z"
is_approved = true
career_page_url = "https://workingatbooking.com/vacancies/?filter-searchphrase=&filter-city=berlin#heading"
latitude = 52.5096131
longitude = 13.3696919
slug = "booking"
tags = ["travel"]
title = "Booking"
updated_at = "2019-06-16T10:36:09.730Z"
