body = "#ecommerce site for #computer #gaming hardware"
created_at = "2018-02-01T20:53:21.440Z"
is_approved = true
carreer_page_url = "https://caseking.recruitee.com/"
job_board_provider = "recruitee"
job_board_hostname = "caseking"
latitude = 52.530086
longitude = 13.312013
slug = "caseking"
tags = ["ecommerce", "computer", "gaming"]
title = "caseking"
updated_at = "2019-06-16T10:36:08.535Z"
