body = "#startup #big-data #mathematics #software"
created_at = "2018-02-08T08:46:54.014Z"
is_approved = true
career_page_url = "http://celeraone.com/en/careers"
latitude = 52.54101
longitude = 13.39238
slug = "celeraone"
tags = ["startup", "big-data", "mathematics", "software"]
title = "Celeraone"
updated_at = "2019-06-16T10:36:08.540Z"
