body = "Providing online patient recruitment, retention, patient surveys, study feasibility and site selection services for clinical trials. #health #startup #life-science"
created_at = "2019-10-22T08:27:46.472Z"
is_approved = true
career_page_url = "https://www.clariness.com/careers/"
slug = "clariness"
tags = ["health", "startup", "life-science"]
title = "Clariness"
