body = "Hand-picked consultants. #consulting"
created_at = "2020-02-29T18:07:02.000Z"
is_approved = true
career_page_url = "https://comatch-gmbh-jobs.personio.de"
job_board_provider = "personio"
job_board_hostname = "comatch-gmbh-jobs"
company_url = "https://www.comatch.com/"
latitude = 52.52727
longitude = 13.3419823
slug = "comatch"
tags = ["consulting"]
title = "comatch"
