body = "IT partner for innovative and growing companies; #it"
created_at = "2019-09-16T09:01:38.886Z"
is_approved = true
career_page_url = "https://www.commehr.de/karriere"
latitude = 52.4989184
longitude = 13.3353184
slug = "commehr"
tags = ["it"]
title = "commehr"
