body = "#french speaking #language #job-board"
created_at = "2017-06-28T20:31:44.037Z"
is_approved = true
career_page_url = "http://www.connexion-emploi.com/de/offers#t=&page=1&geolocation=31-7"
slug = "connexion-emploi"
tags = ["french", "languages", "job-board"]
title = "Connexion Emploi"
updated_at = "2019-06-16T10:36:09.624Z"
