body = "Generalist #job-board"
created_at = "2017-06-28T20:22:06.805Z"
is_approved = true
career_page_url = "http://berlin.en.craigslist.de"
slug = "craigslist"
tags = ["job-board"]
title = "Craigslist"
updated_at = "2019-06-16T10:36:08.536Z"
