body = "#artist and #creative oriented #job-board"
created_at = "2017-06-28T20:32:24.548Z"
is_approved = true
career_page_url = "http://www.creative-city-berlin.de/de/jobs/"
slug = "creative-city-berlin"
tags = ["artist", "creative", "job-board"]
title = "Creative City Berlin"
updated_at = "2019-06-16T10:36:08.539Z"
