body = "#startup"
created_at = "2017-06-28T20:28:26.494Z"
is_approved = true
career_page_url = "http://hire.jobvite.com/CompanyJobs/Careers.aspx?c=qrR9Vfw6&s=Website&nl=1&page=Jobs"
latitude = 52.5130762
longitude = 13.4553134
slug = "dcmn"
tags = ["startup"]
title = "DCMN"
updated_at = "2019-06-16T10:36:08.529Z"
