body = "Delivery Hero is an online #food #delivery service"
created_at = "2017-06-28T20:29:58.350Z"
is_approved = true
career_page_url = "https://www.deliveryhero.com/career/jobs/#!/"
latitude = 52.5170497
longitude = 13.3906159
slug = "delivery-hero"
tags = ["food", "delivery"]
title = "Delivery Hero"
updated_at = "2019-06-16T10:36:09.729Z"
