body = "German railway company. #db #train #transport #railway"
created_at = "2018-02-09T19:40:15.421Z"
is_approved = true
career_page_url = "https://karriere.deutschebahn.com/de/de/suche/stellenboerse/?textquery=&cityquery=Berlin"
slug = "deutsche-bahn"
tags = ["db", "train", "transport", "railway"]
title = "Deutsche Bahn"
updated_at = "2019-06-16T10:36:09.636Z"
