body = "Windows and door manufacturing and setup. #industry"
created_at = "2018-02-15T09:32:57.606Z"
is_approved = true
career_page_url = "https://www.deutsche-fensterbau.de/jobs/"
slug = "deutsche-fensterbau"
tags = ["industry"]
title = "Deutsche Fensterbau"
updated_at = "2019-06-16T10:36:09.732Z"
