body = "DHL is the global market leader in the logistics industry. DHL commits its expertise in international parcel, express, air and ocean freight, road and rail ... #logistics"
created_at = "2018-02-09T14:43:02.723Z"
is_approved = true
career_page_url = "https://www.dpdhl.jobs/search-jobs/Berlin%2C%20Land%20Berlin%2C%20Germany/1886/4/2921044-2950157-2950159/52x52437/13x41053/50/2"
slug = "dhl"
tags = ["logistics"]
title = "DHL"
updated_at = "2019-06-16T10:36:09.626Z"
