body = "#job-board for #graphic-design, #web-design, #illustration, #photography"
created_at = "2018-02-03T11:29:20.252Z"
is_approved = true
career_page_url = "https://dribbble.com/jobs?location=Berlin"
slug = "dribbble"
tags = ["job-board", "graphic-design", "web-design", "illustration", "photography"]
title = "Dribbble"
updated_at = "2019-06-16T10:36:09.730Z"
