body = "Generalist #job-board"
created_at = "2017-06-28T20:21:56.161Z"
is_approved = true
career_page_url = "http://kleinanzeigen.ebay.de/anzeigen/s-jobs/berlin/c102l3331"
slug = "ebay-kleinanzeigen"
tags = ["job-board"]
title = "Ebay Kleinanzeigen"
updated_at = "2019-06-16T10:36:09.641Z"
