body = "Video game and #software development company; #games"
created_at = "2018-02-05T13:24:34.907Z"
is_approved = true
career_page_url = "https://epicgames.wd5.myworkdayjobs.com/Epic_Games/1/refreshFacet/318c8bb6f553100021d223d9780d30be"
slug = "epic"
tags = ["software", "games"]
title = "Epic"
updated_at = "2019-06-16T10:36:09.736Z"
