body = "#bio #eco #food #startup"
created_at = "2018-02-02T10:43:41.836Z"
is_approved = true
career_page_url = "https://frechefreunde.de/jobs"
latitude = 52.54059
longitude = 13.40675
slug = "erdbär-gmbh-freche-freunde"
tags = ["bio", "eco", "food", "startup"]
title = " Erdbär GmbH Freche Freunde"
updated_at = "2019-06-16T10:36:09.744Z"
