body = "Phone as a Service. Equips workforces with smartphones and tablets #startup #phone #corporate"
created_at = "2020-02-29T13:03:56.000Z"
is_approved = true
career_page_url = "https://everphone.join.com/"
latitude = 52.5079038
longitude = 13.3911477
slug = "everphone"
tags = ["startup", "phone", "corporate"]
title = "everphone"
