body = "#social-media service. #multinational"
created_at = "2018-01-27T09:35:09.370Z"
is_approved = true
career_page_url = "https://www.facebook.com/careers/search/?q=&location=berlin"
slug = "facebook"
tags = ["social-media", "multinational"]
title = "Facebook"
updated_at = "2019-06-16T10:36:08.535Z"
