body = "financeAds International GmbH is an international #affiliate network with a focus on the #financial sector. It helps financial service providers to market their products and services online, offering a transaction-based pricing model"
created_at = "2018-02-01T09:33:27.651Z"
is_approved = true
career_page_url = "https://www.financeads.com/uk-en/aboutus/jobs/"
latitude = 52.5219252
longitude = 13.3553899
slug = "financeads-international"
tags = ["affiliate", "financial"]
title = "financeAds International"
updated_at = "2019-06-16T10:36:08.532Z"
