body = "Conscious #fashion online store"
created_at = "2018-11-20T16:17:58.299Z"
is_approved = true
career_page_url = "https://www.fineyellow.com/join-us/"
latitude = 52.5335917
longitude = 13.4295176
slug = "fine-yellow"
tags = ["fashion"]
title = "Fine Yellow"
updated_at = "2019-06-16T10:36:09.731Z"
