body = "#finance #bank #startup"
created_at = "2019-07-17T12:12:44.295Z"
is_approved = true
career_page_url = "https://finreachgmbh.recruitee.com/"
latitude = 52.50817
longitude = 13.32913
slug = "finreach"
tags = ["finance", "bank", "startup"]
title = "finreach"
