body = "Radio & Music Streaming #radio #music"
created_at = "2018-02-15T10:38:04.579Z"
is_approved = true
career_page_url = "https://www.fluxfm.de/jobs/"
latitude = 52.5029717
longitude = 13.4406634
slug = "fluxfm"
tags = ["radio", "music"]
title = "FluxFm"
updated_at = "2019-06-16T10:36:09.729Z"
