body = "Online #news outlet specializing in #android; #tech"
created_at = "2017-06-28T20:28:15.580Z"
is_approved = true
career_page_url = "http://fonpit.com/all-jobs"
latitude = 52.525296
longitude = 13.4210927
slug = "fontpit-androidpit"
tags = ["news", "android", "tech"]
title = "Fontpit / Androidpit"
updated_at = "2019-06-16T10:36:08.539Z"
