body = "Online cross platform #games #community"
created_at = "2017-06-28T20:23:46.183Z"
is_approved = true
career_page_url = "http://inside.gameduell.com/jobs/"
latitude = 52.513353
longitude = 13.395566
slug = "gameduell"
tags = ["games", "community"]
title = "Gameduell"
updated_at = "2019-06-16T10:36:08.517Z"
