body = "#recruiting agency specialists in #technology; #hr"
created_at = "2017-06-28T20:37:07.455Z"
is_approved = true
career_page_url = "http://global-m.co.uk/jobs/?country=all&location=berlin&role=all&sector=all&seniority=all&type=all&salaryRange=all"
slug = "global-m"
tags = ["recruiting", "technology", "hr"]
title = "Global-m"
updated_at = "2019-06-16T10:36:09.639Z"
