body = "#german #language #job-board"
created_at = "2017-06-28T20:31:02.792Z"
is_approved = true
career_page_url = "http://www.gruenderszene.de/jobboerse/"
slug = "gruenderszene"
tags = ["german", "languages", "job-board"]
title = "Gruenderszene"
updated_at = "2019-06-16T10:36:08.536Z"
