body = "#pr #advertising #agency"
created_at = "2017-06-28T20:37:51.626Z"
is_approved = true
career_page_url = "http://www.heimat-berlin.com/jobs"
slug = "heimat"
tags = ["pr", "advertising", "agency"]
title = "Heimat"
updated_at = "2019-06-16T10:36:09.625Z"
