body = "Provides mapping and location data and related services to individuals and companies #tech #map"
created_at = "2018-02-01T11:40:31.805Z"
is_approved = true
career_page_url = "https://www.here.com/en/careers/jobs#/location:Europe%2C%20Germany%2C%20Berlin/"
slug = "here"
tags = ["tech", "map"]
title = "Here"
updated_at = "2019-06-16T10:36:09.624Z"
