body = "Home24 is an online #shop presenting #fournitures and #decoration items"
created_at = "2017-06-28T20:26:55.910Z"
is_approved = true
career_page_url = "http://jobs.jobvite.com/home24.de/"
slug = "home24de"
tags = ["shop", "fournitures", "decoration"]
title = "Home24.de"
updated_at = "2019-06-16T10:36:09.629Z"
