body = "#interior-design #ecommerce platform; #startup #design"
created_at = "2018-02-20T19:51:15.961Z"
is_approved = true
career_page_url = "https://www.homify.de/jobs"
slug = "homify"
tags = ["interior-design", "ecommerce", "startup", "design"]
title = "Homify"
updated_at = "2019-06-16T10:36:08.535Z"
