body = "Honeypot is a #tech focused #job-board #europe"
created_at = "2017-06-28T20:35:06.254Z"
is_approved = true
career_page_url = "https://jobs.lever.co/honeypot"
slug = "honeypot"
tags = ["tech", "job-board", "europe"]
title = "Honeypot"
updated_at = "2019-06-16T10:36:08.536Z"
