body = "#job-board for career in german #hotels. #hospitality"
created_at = "2018-02-28T09:08:21.553Z"
is_approved = true
career_page_url = "https://www.hotelcareer.de/"
slug = "hotel-career"
tags = ["job-board", "hotels", "hospitality"]
title = "Hotel Career"
updated_at = "2019-06-16T10:36:08.531Z"
