body = "#online #web-tv platform creating #video oriented #content ; #tv"
created_at = "2017-06-28T20:38:28.113Z"
is_approved = true
career_page_url = "http://hyperbole.de/jobs/"
latitude = 52.5160485
longitude = 13.4573025
slug = "hyperbole"
tags = ["online", "web-tv", "video", "content", "tv"]
title = "Hyperbole"
updated_at = "2019-06-16T10:36:09.626Z"
