body = "#job-board for #english language jobs"
created_at = "2017-06-28T20:25:23.887Z"
is_approved = true
career_page_url = "http://www.jobinberlin.com"
slug = "job-in-berlin"
tags = ["job-board", "english"]
title = "Job in Berlin"
updated_at = "2019-06-16T10:36:08.532Z"
