body = "general purpose #job-board"
created_at = "2018-02-01T13:22:24.348Z"
is_approved = true
career_page_url = "https://joblift-jobs.personio.de"
job_board_provider = "personio"
job_board_hostname = "joblift-jobs"
slug = "joblift"
tags = ["job-board"]
title = "Joblift"
updated_at = "2019-06-16T10:36:09.626Z"
