body = "#english speaking #language #job-board"
created_at = "2017-06-28T20:21:33.747Z"
is_approved = true
career_page_url = "http://www.jobsinberlin.eu/"
slug = "jobs-in-berlineu"
tags = ["english", "languages", "job-board"]
title = "Jobs in Berlin.eu"
updated_at = "2019-06-16T10:36:09.629Z"
