body = "English speaking language job board"
created_at = "2017-06-28T20:21:33.747Z"
is_approved = true
career_page_url = "http://www.jobsinberlin.eu"
slug = "jobs-in-berlin-eu"
tags = ["english", "languages", "job-board"]
title = "Jobs in Berlin.eu"
updated_at = "2020-04-09T08:00:00.629Z"
