body = "JustWatch offers a solution to browse through your favorite #movies or #tv shows to see if they are available for #streaming at any of your favorite providers or in the #cinema"
created_at = "2017-06-28T20:38:00.741Z"
is_approved = true
career_page_url = "https://www.justwatch.com/us/talent"
latitude = 52.5134213
longitude = 13.455574
slug = "justwatch"
tags = ["movies", "tv", "streaming", "cinema"]
title = "JustWatch"
updated_at = "2019-06-16T10:36:09.747Z"
