body = "#coworking spaces in Berlin"
created_at = "2019-05-15T09:40:58.000Z"
is_approved = true
career_page_url = "https://www.knotel.com/careers/"
slug = "knotel"
tags = ["coworking"]
title = "Knotel"
updated_at = "2019-06-16T10:36:09.638Z"
