body = "#startup focusing on mobile video #games"
created_at = "2019-05-15T21:09:08.628Z"
is_approved = true
career_page_url = "https://www.kolibrigames.com/career/positions/"
latitude = 52.5007378
longitude = 13.3840166
slug = "kolibri"
tags = ["startup", "games"]
title = "Kolibri "
updated_at = "2019-06-16T10:36:09.730Z"
