body = "#fashion store"
created_at = "2018-10-24T09:30:39.890Z"
is_approved = true
career_page_url = "https://maisonbaum.com/pages/jobs"
slug = "maison-baum"
tags = ["fashion"]
title = "Maison Baum"
updated_at = "2019-06-16T10:36:09.732Z"
