body = "Springer Nature is an #academic #publishing company"
created_at = "2017-06-28T20:38:54.258Z"
is_approved = true
career_page_url = "https://www.megaport.com/careers/"
slug = "megaport"
tags = ["academic", "publishing"]
title = "Megaport"
updated_at = "2019-06-16T10:36:09.626Z"
