body = "automobile; #transport "
created_at = "2019-05-09T09:18:52.833Z"
is_approved = true
career_page_url = "https://www.mercedes-benz.io/jobs/"
latitude = 52.5111162
longitude = 13.4023339
slug = "mercedes-benzio"
tags = ["transport"]
title = "Mercedes-Benz.io"
updated_at = "2019-06-16T10:46:49.000Z"
