body = "#startup #job-board"
created_at = "2019-02-18T23:35:00.471Z"
is_approved = true
career_page_url = "https://meritocracy.is/en/jobs/berlin"
slug = "meritocracy"
tags = ["startup", "job-board"]
title = "Meritocracy"
updated_at = "2019-06-16T10:36:09.640Z"
