body = "#startup provinding #coworking space and shared-office space"
created_at = "2018-02-05T21:27:18.884Z"
is_approved = true
career_page_url = "https://www.mindspace.me/jobs/?position=66.606"
slug = "mindspace"
tags = ["startup", "coworking"]
title = "Mindspace"
updated_at = "2019-06-16T10:36:08.535Z"
