body = "online #video #data services; #tech #startup"
created_at = "2017-06-28T20:26:39.836Z"
is_approved = true
career_page_url = "http://mixd.tv/careers.html"
latitude = 52.523102
longitude = 13.366863
slug = "mixdtv"
tags = ["video", "data", "tech", "startup"]
title = "Mixd.tv"
updated_at = "2019-06-16T10:36:08.531Z"
