body = "#movie streaming website; #startup #media"
created_at = "2019-05-05T05:59:47.479Z"
is_approved = true
career_page_url = "https://mubi.com/jobs"
slug = "mubi"
tags = ["movie", "startup", "media"]
title = "Mubi"
updated_at = "2019-06-16T10:36:08.537Z"
