body = "N26 is the Mobile #bank. Free bank account and Mastercard that you can manage directly from your phone. #startup"
created_at = "2017-06-28T20:30:23.977Z"
is_approved = true
career_page_url = "https://n26.com/jobs"
latitude = 52.5098092
longitude = 13.3811811
slug = "n26"
tags = ["bank", "startup"]
title = "N26"
updated_at = "2019-06-16T10:36:09.782Z"
