body = "#startup"
created_at = "2018-02-10T15:20:19.236Z"
is_approved = true
career_page_url = "https://www.orderbird.com/en/careers"
latitude = 52.5018616
longitude = 13.4112619
slug = "orderbird"
tags = ["startup"]
title = "orderbird"
updated_at = "2019-06-16T10:36:08.535Z"
