body = "#employment-agency and #recruitment-agency for #temporary-work and permanent staffing; #workforce #job-board"
created_at = "2018-02-03T18:52:15.376Z"
is_approved = true
career_page_url = "https://www.randstad.de/fuer-bewerber/jobsuche/city/berlin%2B25?items_per_page=10"
slug = "randstad"
tags = ["employment-agency", "recruitment-agency", "temporary-work", "workforce", "job-board"]
title = "Randstad"
updated_at = "2019-06-16T10:36:09.639Z"
