body = "#iot #tech company"
created_at = "2018-01-25T11:34:55.098Z"
is_approved = true
career_page_url = "https://relayr.io/en/jobs"
latitude = 52.4900733
longitude = 13.3894672
slug = "relayr"
tags = ["iot", "tech"]
title = "Relayr"
updated_at = "2019-06-16T10:36:09.728Z"
