body = "#fitness"
created_at = "2018-02-01T20:36:36.701Z"
is_approved = true
career_page_url = "https://www.mcfit-global-group.com/de/karriere/jobs/mcfit/"
latitude = 52.52871
longitude = 13.41623
slug = "rsg-group-gmbh-mc-fit"
tags = ["fitness"]
title = " RSG Group GmbH (Mc Fit)"
updated_at = "2019-06-16T10:36:09.731Z"
