body = "#startup"
created_at = "2018-02-22T00:24:22.218Z"
is_approved = true
career_page_url = "https://SnapEngage.com/careers"
latitude = 52.4610669
longitude = 13.3251054
slug = "snapengage"
tags = ["startup"]
title = "SnapEngage"
updated_at = "2019-06-16T10:36:08.535Z"
