body = "#music streaming platform; #startup #tech"
created_at = "2017-06-28T20:20:54.577Z"
is_approved = true
career_page_url = "https://soundcloud.com/jobs"
latitude = 52.5368168
longitude = 13.394882
slug = "soundcloud"
tags = ["music", "startup", "tech"]
title = "Soundcloud"
updated_at = "2019-06-16T10:36:09.731Z"
