body = "Fitness center group #fitness #sport #gym #yoga"
created_at = "2018-02-09T15:13:05.323Z"
is_approved = true
career_page_url = "http://superfit.club/jobs/"
slug = "superfit"
tags = ["fitness", "sport", "gym", "yoga"]
title = "SuperFit"
updated_at = "2019-06-16T10:36:09.638Z"
