body = "#communication and #pr #agency"
created_at = "2018-02-09T15:47:57.570Z"
is_approved = true
career_page_url = "https://sustentio.eu/category/career/"
latitude = 52.5008709
longitude = 13.4129852
slug = "sustentio"
tags = ["communication", "pr", "agency"]
title = "Sustentio"
updated_at = "2019-06-16T10:36:09.747Z"
