body = "Telamo is a german #music #label"
created_at = "2017-06-28T20:34:12.853Z"
is_approved = true
career_page_url = "http://www.telamo.de/job/"
slug = "telamo"
tags = ["music", "label"]
title = "Telamo"
updated_at = "2019-06-16T10:36:09.735Z"
