body = "#it company building #software for public #blockchain"
created_at = "2017-06-28T20:40:44.624Z"
is_approved = true
career_page_url = "https://tendermint.com/careers"
slug = "tendermint"
tags = ["it", "software", "blockchain"]
title = "Tendermint"
updated_at = "2019-06-16T10:36:09.740Z"
