body = "Tillhub provides POS (Point Of Sale) system for retailers and service providers. #startup #operations"
created_at = "2019-06-28"
is_approved = true
career_page_url = "https://www.tillhub.de/jobs/"
latitude = 52.5031011
longitude = 13.3584261
slug = "tillhub"
tags = ["startup", "operations"]
title = "Tillhub"
