body = "#travel platfom, also for #hotels and #events. #startup"
created_at = "2018-11-20T16:14:01.931Z"
is_approved = true
career_page_url = "https://www.travelcircus.de/jobs"
latitude = 52.5639598
longitude = 13.3541097
slug = "travelcircus"
tags = ["travel", "hotels", "events", "startup"]
title = "Travelcircus"
updated_at = "2019-06-16T10:36:09.638Z"
