carreer_page_url = "https://up42gmbh.recruitee.com/"
title = "UP42"
body = "UP42 brings data from satellites, drones, and IoT devices together with analytics tools to detect changes, monitor trends, and identify objects. We’re making it easy to not only see our planet but to understand it too. "
tags = ["startup", "satellites", "iot"]
address = "Ohlauer Str. 43"
postal_code = "10999"
city="berlin"
country="germany"
company_url = "https://up42.com"
slug = "up42"
latitude = 52.493882
longitude = 13.430114
linkedin_url = "https://www.linkedin.com/company/up42"
twitter_url = "https://twitter.com/up42official"
instagram_url = "https://www.instagram.com/up42official"
facebook_url = "https://www.facebook.com/up42Official"
created_at = "2020-04-24T19:35:18.626Z"
updated_at = "2020-04-24T19:35:18.626Z"
is_approved = true
draft = false
