body = "#startup #navigation #ride-sharing #transport"
created_at = "2018-02-09T06:44:05.203Z"
is_approved = true
career_page_url = "https://ridewithvia.com/jobs/"
slug = "via"
tags = ["startup", "navigation", "ride-sharing", "transport"]
title = "Via"
updated_at = "2019-06-16T10:36:08.533Z"
