body = "Clinic group, network for health."
created_at = "2018-02-09T20:10:41.012Z"
is_approved = true
career_page_url = "http://www.vivantes-karriere.de/nc/jetzt-bewerben/"
slug = "vivantes"
tags = ["health", "clinic", "medicine", "nurse", "healthcare", "hostpital"]
title = " Vivantes"
updated_at = "2019-06-16T10:36:09.744Z"
