body = "#communication #agency"
created_at = "2018-02-02T10:42:17.679Z"
is_approved = true
career_page_url = "https://www.vybebrothers.com/jobs"
latitude = 52.5077221
longitude = 13.4542457
slug = "vybe-brothers"
tags = ["communication", "agency"]
title = "Vybe Brothers"
updated_at = "2019-06-16T10:36:09.622Z"
