body = "WeWork is a foreign corporation that provides shared #workspaces, technology #startup subculture communities, and services for entrepreneurs, freelancers, startups, small businesses and large enterprises."
created_at = "2018-01-29T19:19:26.915Z"
is_approved = true
career_page_url = "https://wework.wd1.myworkdayjobs.com/Corporate/2/refreshFacet/318c8bb6f553100021d223d9780d30be"
slug = "wework"
tags = ["workspaces", "startup"]
title = "WeWork"
updated_at = "2019-06-16T10:36:09.734Z"
