body = "Norwegian #chemical company specialized in the production of nitrogen fertilizers and other nitrogen-based chemicals"
created_at = "2017-10-25T16:02:19.836Z"
is_approved = true
career_page_url = "http://yara.com/careers/vacant_positions/"
slug = "yara"
tags = ["chemical"]
title = "yara"
updated_at = "2019-06-16T10:36:09.640Z"
