body = "#vpn and #cyber-security solutions to encrypt a user web trafic; #tech"
created_at = "2017-06-28T20:34:58.558Z"
is_approved = true
career_page_url = "https://zenmate.com/jobs"
latitude = 52.4943559
longitude = 13.4367892
slug = "zenmate"
tags = ["vpn", "cyber-security", "tech"]
title = "ZenMate"
updated_at = "2019-06-16T10:36:09.735Z"
